name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
        
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Debug - PHP modules
      run: php -m

    - name: Run unit tests with coverage
      run: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml

    - name: Run BDD tests
      run: vendor/bin/behat

    - name: Debug - List files
      run: ls -la

    - name: Debug - Display coverage.xml content
      run: cat coverage.xml
      if: always()

    - name: Check code coverage
      run: |
        if [ ! -f coverage.xml ]; then
          echo "coverage.xml file not found!"
          exit 1
        fi
        
        COVERAGE=$(grep -oP '(?<=<coverage generated=".*" line-rate=")[^"]*' coverage.xml)
        if [ -z "$COVERAGE" ]; then
          echo "Failed to extract coverage rate from coverage.xml"
          exit 1
        fi
        
        COVERAGE_PERCENTAGE=$(echo "$COVERAGE * 100" | bc)
        if (( $(echo "$COVERAGE_PERCENTAGE < 80" | bc -l) )); then
          echo "Code coverage is below 80%: $COVERAGE_PERCENTAGE%"
          exit 1
        else
          echo "Code coverage is $COVERAGE_PERCENTAGE%"
        fi

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=LucasMinikel_fiap-tech-challenge-cliente
          -Dsonar.organization=lucasminikel
          -Dsonar.sources=src
          -Dsonar.tests=tests
          -Dsonar.php.tests.reportPath=test-report.xml
          -Dsonar.php.coverage.reportPaths=coverage.xml