name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Necessário para o SonarCloud ver todo o histórico

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests
      run: vendor/bin/phpunit --configuration phpunit.xml

    - name: Run BDD tests
      run: vendor/bin/behat

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=LucasMinikel_fiap-tech-challenge-cliente
          -Dsonar.organization=lucasminikel
          -Dsonar.sources=src
          -Dsonar.tests=tests
          -Dsonar.php.tests.reportPath=test-report.xml